import PropTypes from "prop-types";

const optionsPropType = PropTypes.shape({
  caseRefNo: PropTypes.bool.isRequired,
  openedOn: PropTypes.bool.isRequired,
  closedOn: PropTypes.bool.isRequired,
  lastActioned: PropTypes.bool.isRequired,
  assignedTo: PropTypes.bool.isRequired,
  createdBy: PropTypes.bool.isRequired,
  reviewOn: PropTypes.bool.isRequired,
  contactType: PropTypes.bool.isRequired,
  caseType: PropTypes.bool.isRequired,
  status: PropTypes.bool.isRequired,
  category: PropTypes.bool.isRequired,
  tags: PropTypes.bool.isRequired,
  showCombinedName: PropTypes.bool.isRequired,
  title: PropTypes.bool.isRequired,
  firstname: PropTypes.bool.isRequired,
  surname: PropTypes.bool.isRequired,
  knownAs: PropTypes.bool.isRequired,
  organisationName: PropTypes.bool,
  organisationType: PropTypes.bool,
  postNominal: PropTypes.bool.isRequired,
  constituentEmail: PropTypes.bool.isRequired,
  constituentTelephone: PropTypes.bool.isRequired,
  constituentMobile: PropTypes.bool.isRequired,
  postalAddressLine: PropTypes.bool.isRequired,
  postalAddress1: PropTypes.bool.isRequired,
  postalAddress2: PropTypes.bool.isRequired,
  postalTown: PropTypes.bool.isRequired,
  postalCounty: PropTypes.bool.isRequired,
  postalPostCode: PropTypes.bool.isRequired,
  registeredAddressLine: PropTypes.bool.isRequired,
  registeredAddress1: PropTypes.bool.isRequired,
  registeredAddress2: PropTypes.bool.isRequired,
  registeredSuburb: PropTypes.bool.isRequired,
  registeredState: PropTypes.bool.isRequired,
  registeredPostcode: PropTypes.bool.isRequired,
  summary: PropTypes.bool.isRequired,
  exportName: PropTypes.string.isRequired,
  combinedNameFormat: PropTypes.oneOf([
    "titleInitialSurname",
    "titleFirstnameSurname",
    "titleSurname",
    "firstnameSurname",
    "firstnameOnly",
  ]).isRequired,
  customFields: PropTypes.object.isRequired,
});

export default optionsPropType;
