const defaultOptions = {
  caseRefNo: true,
  openedOn: true,
  closedOn: true,
  lastActioned: true,
  assignedTo: true,
  createdBy: true,
  reviewOn: true,
  contactType: true,
  caseType: true,
  status: true,
  category: true,
  tags: true,
  relatesTo: true,
  showCombinedName: false,
  title: false,
  firstname: false,
  surname: false,
  knownAs: false,
  postNominal: false,
  dob: false,
  gender: false,
  constituentEmail: false,
  constituentTelephone: false,
  constituentMobile: false,
  postalAddressLine: false,
  postalAddress1: false,
  postalAddress2: false,
  postalTown: false,
  postalCounty: false,
  postalPostCode: false,
  registeredAddressLine: false,
  registeredAddress1: false,
  registeredAddress2: false,
  registeredSuburb: false,
  registeredState: false,
  registeredPostcode: false,
  summary: true,
  summaryFull: false,
  organisationName: false,
  organisationType: false,
  exportName: "",
  combinedNameFormat: "titleInitialSurname",
  customFields: {},
};

export default defaultOptions;
