export const getOrgPostalAddress = ({
  address1,
  address2,
  county,
  town,
  postcode,
  registeredAddress1,
  registeredAddress2,
  registeredTown,
  registeredState,
  registeredPostcode,
  registeredStreet,
}) => ({
  address1,
  address2,
  county,
  town,
  postcode,
  registeredAddress1,
  registeredAddress2,
  registeredTown,
  registeredState,
  registeredPostcode,
  registeredStreet,
});
